### ISSUE TITLE
merge opinion about seamly2d fix for appimage generation

### ISSUE THREAD

**Issue by lattice0** [mhitza/docker-linuxdeployqt#2]
Your repo is being used in Seamly2D to create appimages for both seamly2d and seamlyme. The seamly2d's appimage also includes seamlyme, but launching seamlyme from seamly2d wont work because `linuxdeployqt` only attaches the libraries from the binary pointed by seamly2d.desktop, which is seamly2d. In order to also include the dependencies from seamlyme, we have to pass `-executable=/app/usr/bin/seamlyme` to `linuxdeployqt`

So I forked this repo and created a .sh file for seamly2d and another one for seamlyme. Take a look: https://github.com/lucaszanella/docker-linuxdeployqt/tree/41a73d6f8bb6650453da431afb82c7eddcf611f8 (the builder.sh is not being used right now, gonna delete).

This is how it's bein called right now:

```
          mkdir -p /home/runner/local/share/applications /home/runner/local/share/icons/hicolor/256x256

          cp dist/seamly2d.desktop /home/runner/local/share/applications/
          cp share/img/Seamly2D_logo_254x254.png /home/runner/local/share/icons/hicolor/256x256/seamly2d.png

          docker run --cap-add SYS_ADMIN --device /dev/fuse \
            --security-opt apparmor:unconfined --security-opt seccomp=unconfined \
            -v /home/runner/local:/app/usr \
            --rm lucaszanella/linuxdeployqt /bin/bash make_seamly2d_appimage.sh

          mv /home/runner/local/Seamly2D*.AppImage Seamly2D.AppImage
          cp share/img/Seamly2D_logo_254x254.png /home/runner/local/share/icons/hicolor/256x256/seamlyme.png

          rm /home/runner/local/share/applications/seamly2d.desktop
          cp dist/seamlyme.desktop /home/runner/local/share/applications

          docker run --cap-add SYS_ADMIN --device /dev/fuse \
            --security-opt apparmor:unconfined --security-opt seccomp=unconfined \
            -v /home/runner/local:/app/usr \
            --rm lucaszanella/linuxdeployqt /bin/bash make_seamlyme_appimage.sh

          mv /home/runner/local/SeamlyMe*.AppImage SeamlyMe.AppImage
```

with this the seamly2d's appimage correctly included the dependencies for seamly2d and seamlyme and launching seamlye from seamly2d works.

However, since I'm having problems downloading the qt binaries and building my own docker image, I built mine based on yours, see the Dockerfile.

Anyways, what you think of that? How do you think a merge should be done? It looks like this repo is used for Seamly2D project but can be used for others, so this is why I ask, because my repo is specifically for Seamly2D as it included the extra executables in .sh.

I'd like to know how you prefer to merge this

**Comment by lattice0** [comment]
I heard you're gonna merge it today.

I've come with a great solution that will still make docker-linuxdeployqt available for a wider audience. See my new builder.sh file:

https://github.com/lucaszanella/docker-linuxdeployqt/blob/0bdafab9560b91f8d7972dbc11899c1262321095/builder.sh

this is all that needs to change. I'm building everything right now to see if it works

**Comment by lattice0** [comment]
Alright, everything works!

Example of usage:

https://github.com/lucaszanella/Seamly2D/blob/develop/.github/workflows/build-release-assets.yml#L63

Instead of me sending a pull request, can you simply do the changes presented on https://github.com/lucaszanella/docker-linuxdeployqt/blob/0bdafab9560b91f8d7972dbc11899c1262321095/builder.sh?

When I build here, qt downloading always fail!

Once you upload the docker image to the docker hub I can then make the changes on my repo to use your image. 

Also this little update wont break old appimage generation code that uses this repo :)

Thank you very much!

**Comment by lattice0** [comment]
Wrong link of example of usage. 

Correct one: https://github.com/lucaszanella/Seamly2D/blob/a28ea21381c611a464c78989d2c54c9316e17266/.github/workflows/build-release-assets.yml#L66

**Comment by mhitza** [comment]
@lucaszanella I've implemented the change with an additional environmental variable called `EXTRA_BINARIES`, you can see the partial change in this build https://github.com/mhitza/Seamly2D/commit/ff41586d93360a22886d1c90d279283ccd624464

Your solution works well too, it just happened that I had the change made locally beforehand but not committed because of testing issues. It's implemented using bash array syntax and the for statement iterates over the items separated by space and builds up the additional executable arguments as seen in this diff https://github.com/mhitza/docker-linuxdeployqt/commit/e9535c2d597151d1671c2c25f0f1d76d826fc17e

As we're on the Seamly2D topic, on what distro are you running the AppImage builder? I'm using Fedora 32 and the builds through docker that I do locally end up with AppImage's that segfault when they start, as such I'm restricted on running the build/packaging via GitHub at the moment (might be a Fedora issue somehow, as docker itself isn't supported anymore officially on Fedora :shrug: ).

In terms of this container being useful to package other applications, you're right, that is the intention. I have an idea of how that's going to happen moving forward, but at the moment it is used only for Seamly2D.

**Comment by lattice0** [comment]
I tried on my PC on debian 10 64 bits and it worked. Then I trie don the github workflow (ubuntu) and it also worked.

I don't know why you got this error but maybe its because you build on a totally different machine? Don't know, but hte appimage generated by the workflow works.

Thank you for the change, it worked perfectly on my computer and on the workflow :)
