### ISSUE TITLE
Cannot build this image anymore

### ISSUE THREAD

**Issue by lattice0** [mhitza/docker-linuxdeployqt#3]
Hello, I worked on this repo before. It cannot be built anymore

First, I had to modify `ARG QT_VERSION` to 

`ARG QT_VERSION=5.13`

Then I did

`RUN aqt install $QT_VERSION linux desktop -m all && cp -R ./$QT_VERSION/gcc_64/* /usr && rm -rf ./$QT_VERSION`

but it tries to download from qt.io which does not exist anymore

**Comment by lattice0** [comment]
I meant [download.qt.io](download.qt.io)

**Comment by lattice0** [comment]
Context: I'm trying to generate an AppImage for a binary that gives me this:

`ERROR: ldd outputLine: "/app/usr/UltraNoteInfinity: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /app/usr/UltraNoteInfinity)"`

So I thought I should update ubuntu from 16.04 to 18.04 on this docker image, but it cannot be built anymore

**Comment by mhitza** [comment]
Thank you for reporting the issue :+1: . I'll check the build myself later today.

**Comment by mhitza** [comment]
@lucaszanella I have to see what qt installation mirrors are available (that page doesn't load either), so builds are broken until I find those.

On the GLIB_C version, the ubuntu-16.04 image used as base is 2.23 so that's the reason why that project fails.

But since this project has been created until now, the AppImage project went even further back and recommend Ubuntu 14.04/CentOS 6 for builds. For the project you are trying to build I would suggest you switch the dependency requirement to GLIBC_2.23 for the AppImage build to work. The AppImage project is pretty strict on what version of GLIBC it likes to work with. And for the application you are trying to package, specifying an older version of GLIBC shouldn't be an issue. They only added new things, and haven't removed anything between 2.23/2.25 https://abi-laboratory.pro/?view=timeline&l=glibc

**Comment by mhitza** [comment]
I've replaced the standard installation website with the first mirror I got my hands on. Not a fan of hardcoding a mirror, and I think it would be nice if aqtinstall would support that out of the box.

But for now, builds are working again https://github.com/mhitza/docker-linuxdeployqt/actions/runs/501787902
